"""Conversation data model."""

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Conversation:
    """Represents a chat conversation (session).

    Attributes:
        id: Unique identifier (auto-generated by SQLite).
        title: Display title, auto-generated from first user message.
        model: Ollama model name (e.g., 'qwen3:14b').
        system_prompt: Optional system prompt for this conversation.
        created_at: ISO 8601 creation timestamp.
        updated_at: ISO 8601 last update timestamp.
    """

    id: int = 0
    title: str = "New Chat"
    model: str = ""
    system_prompt: str = ""
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "title": self.title,
            "model": self.model,
            "system_prompt": self.system_prompt,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Conversation":
        """Create instance from dictionary (e.g., SQLite row)."""
        return cls(
            id=data.get("id", 0),
            title=data.get("title", "New Chat"),
            model=data.get("model", ""),
            system_prompt=data.get("system_prompt", ""),
            created_at=data.get("created_at", ""),
            updated_at=data.get("updated_at", ""),
        )
