"""Message data model."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal


MessageRole = Literal["system", "user", "assistant"]


@dataclass
class Message:
    """Represents a single chat message.

    Attributes:
        id: Unique identifier (auto-generated by SQLite).
        conversation_id: Foreign key to the parent conversation.
        role: Message role: 'system', 'user', or 'assistant'.
        content: Message body (plain text or Markdown).
        created_at: ISO 8601 creation timestamp.
    """

    id: int = 0
    conversation_id: int = 0
    role: MessageRole = "user"
    content: str = ""
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> dict:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "conversation_id": self.conversation_id,
            "role": self.role,
            "content": self.content,
            "created_at": self.created_at,
        }

    def to_api_format(self) -> dict:
        """Convert to Ollama API messages format.

        Returns:
            dict with 'role' and 'content' keys as expected by /api/chat.
        """
        return {
            "role": self.role,
            "content": self.content,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Message":
        """Create instance from dictionary (e.g., SQLite row or API response)."""
        return cls(
            id=data.get("id", 0),
            conversation_id=data.get("conversation_id", 0),
            role=data.get("role", "user"),
            content=data.get("content", ""),
            created_at=data.get("created_at", ""),
        )
